// <auto-generated />
using System;
using ManagerPlanner.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManagerPlanner.Core.Migrations
{
    [DbContext(typeof(PlanningDbContext))]
    partial class PlanningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ManagerPlanner.Core.Domain.ChecklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("ParentId");

                    b.HasIndex("WorkItemId");

                    b.ToTable("ChecklistItems");
                });

            modelBuilder.Entity("ManagerPlanner.Core.Domain.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MeetingDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MeetingDate");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("ManagerPlanner.Core.Domain.Objective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyResult")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("ManagerPlanner.Core.Domain.ProgressNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPromise")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NoteDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PromisedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("MeetingId");

                    b.HasIndex("WorkItemId");

                    b.ToTable("ProgressNotes");
                });

            modelBuilder.Entity("ManagerPlanner.Core.Domain.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ManagerPlanner.Core.Domain.StatusChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChangedById")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FromStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<int>("ToStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("ChangedUtc");

                    b.HasIndex("WorkItemId");

                    b.ToTable("StatusChanges");
                });

            modelBuilder.Entity("ManagerPlanner.Core.Domain.TaskOwner", b =>
                {
                    b.Property<int>("WorkItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkItemId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskOwners");
                });

            modelBuilder.Entity("ManagerPlanner.Core.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ManagerPlanner.Core.Domain.WorkItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiscoveredInMeetingId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDiscovered")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ObjectiveId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("Deadline");

                    b.HasIndex("DiscoveredInMeetingId");

                    b.HasIndex("ObjectiveId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.ToTable("WorkItems");
                });

            modelBuilder.Entity("ManagerPlanner.Core.Domain.ChecklistItem", b =>
                {
                    b.HasOne("ManagerPlanner.Core.Domain.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ManagerPlanner.Core.Domain.ChecklistItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManagerPlanner.Core.Domain.WorkItem", "WorkItem")
                        .WithMany("Checklist")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Parent");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("ManagerPlanner.Core.Domain.Meeting", b =>
                {
                    b.HasOne("ManagerPlanner.Core.Domain.User", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ManagerPlanner.Core.Domain.Project", "Project")
                        .WithMany("Meetings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ManagerPlanner.Core.Domain.Objective", b =>
                {
                    b.HasOne("ManagerPlanner.Core.Domain.Project", "Project")
                        .WithMany("Objectives")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ManagerPlanner.Core.Domain.ProgressNote", b =>
                {
                    b.HasOne("ManagerPlanner.Core.Domain.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManagerPlanner.Core.Domain.Meeting", "Meeting")
                        .WithMany("Notes")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ManagerPlanner.Core.Domain.WorkItem", "WorkItem")
                        .WithMany("Notes")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Meeting");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("ManagerPlanner.Core.Domain.Project", b =>
                {
                    b.HasOne("ManagerPlanner.Core.Domain.User", "Owner")
                        .WithMany("OwnedProjects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ManagerPlanner.Core.Domain.StatusChange", b =>
                {
                    b.HasOne("ManagerPlanner.Core.Domain.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManagerPlanner.Core.Domain.WorkItem", "WorkItem")
                        .WithMany("StatusHistory")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("ManagerPlanner.Core.Domain.TaskOwner", b =>
                {
                    b.HasOne("ManagerPlanner.Core.Domain.User", "User")
                        .WithMany("OwnedTasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagerPlanner.Core.Domain.WorkItem", "WorkItem")
                        .WithMany("Owners")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("ManagerPlanner.Core.Domain.WorkItem", b =>
                {
                    b.HasOne("ManagerPlanner.Core.Domain.User", "Assignee")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ManagerPlanner.Core.Domain.Meeting", "DiscoveredInMeeting")
                        .WithMany("DiscoveredTasks")
                        .HasForeignKey("DiscoveredInMeetingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ManagerPlanner.Core.Domain.Objective", "Objective")
                        .WithMany("Tasks")
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ManagerPlanner.Core.Domain.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("DiscoveredInMeeting");

                    b.Navigation("Objective");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ManagerPlanner.Core.Domain.ChecklistItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("ManagerPlanner.Core.Domain.Meeting", b =>
                {
                    b.Navigation("DiscoveredTasks");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("ManagerPlanner.Core.Domain.Objective", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ManagerPlanner.Core.Domain.Project", b =>
                {
                    b.Navigation("Meetings");

                    b.Navigation("Objectives");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ManagerPlanner.Core.Domain.User", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("OwnedProjects");

                    b.Navigation("OwnedTasks");
                });

            modelBuilder.Entity("ManagerPlanner.Core.Domain.WorkItem", b =>
                {
                    b.Navigation("Checklist");

                    b.Navigation("Notes");

                    b.Navigation("Owners");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
